<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-06-05T10:51:43Z" name="Surefire suite" finished-at="2018-06-05T10:51:43Z" duration-ms="55">
    <groups>
    </groups>
    <test started-at="2018-06-05T10:51:43Z" name="Surefire test" finished-at="2018-06-05T10:51:43Z" duration-ms="55">
      <class name="TestCase">
      <test-method signature="test()[pri:0, instance:TestCase@4b14c583]" started-at="2018-06-05T17:51:43Z" name="test" finished-at="2018-06-05T17:51:43Z" duration-ms="47"
                   status="FAIL">
      <exception class="org.testng.Assert.fail">
        <message>
          <![CDATA[Assertion message from test]]>
        </message>
        <full-stacktrace>
          <![CDATA[org.testng.Assert.fail: Assertion message from test
      at TestCase.test(Unknown Source)]]>
        </full-stacktrace>
      </exception> <!-- java.lang.AssertionError -->
      <reporter-output>
      </reporter-output>
    </test